[package]
name = "rustybf"
version = "0.1.0"
authors = ["Marco Cameriero <me@marcocameriero.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4.7"
env_logger = "0.6.2"
lazy_static = "1.3.0"
